language: python
python: 2.7
env:
  - WINEENV=py27
before_install:
  - git clone https://github.com/WineAsCI/python-lib-template.git
  - python-lib-template/.travis-setup.sh
install:
  - /opt/wine-staging/bin/wine 'C:\Python27\Scripts\pip.exe' install -r boto/requirements.txt
script: cd boto && /opt/wine-staging/bin/wine 'C:\Python27\Python.exe' tests/test.py default
